source: prerecorded # one of camera_jetson, camera, prerecorded

source_settings:
  increase_brightness: 0
  mirror: true

  # only used with jetson camera, no live-reload
  camera_jetson:
    width: 1280
    height: 720
    display_width: 1280
    display_height: 720
    flip: 0
    zoom: 1.00
    framerate: 25

  # only used with usb/builtin camera, no live-reload
  camera:
    location: 0

  # only used with pre-recorded file, no live-reload
  prerecorded:
    #location: tests/data/generated/%d.png
    #location: tests/data/kat_im_buero/%d.png
    location: tests/data/kat+petter.webm


recognition:
  # every x frames, recognition should be run
  framerate: 10

  models:
     directory: "models" # no live-reload
     stack: "CNN+dlibcrop+openface+dot"   # do not use CNN on laptop; # no live-reload
     face_detection:
       scale: 0.5
       max_num_faces: 5
     frontal_detection:
       nose_centered_tolerance_x: 0.1
       nose_centered_tolerance_y: 0.1
     matching:
       excellent_match_cutoff: 0.2
       good_match_cutoff: 0.4
       poor_match_cutoff: 0.6
       new_face_cutoff: 1.0

  database:
     location: "database.pkl"  # no live-reload
     backup_frequency: 100  # every x frames

display:
  debug: true
  fullscreen: false
  thumbnail_size: 75
  stars_height: 20
  num_matches: 3
  num_matches_debug: 3
  max_age_recognition_result: 1000   # in milliseconds
  display_time_registration_result: 3000  # milliseconds



