camera:
  # following camera parameters only used when running on jetson
  width: 1280
  height: 720
  flip: 0
  zoom: 1.00
  framerate: 15

prerecorded_frames: tests/frames/%d.png

recognition:
  # every x frames, recognition should be run
  framerate: 3
  # recognition results older than x frames will be discarded
  results_max_age: 20

  models:
     directory: "models"
     stack: "HOG+dlibcrop+openface"   # do not use CNN on laptop
     face_detection:
       scale: 0.5

  database:
     location: "database.pkl"
     backup_frequency: 100  # every x frames

display:
  width: 1280
  height: 720
  fullscreen: false
  face_info_max_age: 4



