source: camera # one of camera_jetson, camera, prerecorded

source_settings:
  increase_brightness: 0
  mirror: true

  # only used with jetson camera, no live-reload
  camera_jetson:
    width: 1280
    height: 720
    display_width: 1280
    display_height: 720
    flip: 0
    zoom: 1.00
    framerate: 15

  # only used with usb/builtin camera, no live-reload
  camera:
    location: 0

  # only used with pre-recorded file, no live-reload
  prerecorded:
    # location: tests/data/generated/%d.png
    location: tests/data/kat_im_buero/%d.png
    # location: tests/data/kat+petter.webm


recognition:
  # every x frames, recognition should be run
  framerate: 3
  # recognition results older than x frames will be discarded
  results_max_age: 20

  models:
     directory: "models" # no live-reload
     stack: "HOG+dlibcrop+openface+dot"   # do not use CNN on laptop; # no live-reload
     face_detection:
       scale: 0.5
     frontal_detection:
       nose_centered_tolerance_x: 0.05
       nose_centered_tolerance_y: 0.05
     matching:
       excellent_match_cutoff: 0.2
       good_match_cutoff: 0.4
       poor_match_cutoff: 0.6
       new_face_cutoff: 1.0

  database:
     location: "database.pkl"  # no live-reload
     backup_frequency: 100  # every x frames

display:
  debug: true
  fullscreen: false
  thumbnail_size: 100
  num_matches: 3
  num_matches_debug: 5



